name: Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push images
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/auth-service:${{ github.sha }}
          docker build -f services/auth/Dockerfile.prod -t $IMAGE .
          docker push $IMAGE

          IMAGE2=ghcr.io/${{ github.repository }}/user-service:${{ github.sha }}
          docker build -f services/user/Dockerfile -t $IMAGE2 services/user
          docker push $IMAGE2

          IMAGE3=ghcr.io/${{ github.repository }}/course-service:${{ github.sha }}
          docker build -f services/course/Dockerfile -t $IMAGE3 services/course
          docker push $IMAGE3

      - name: Post-build message
        run: echo "Images pushed to ghcr.io/${{ github.repository }}"
